### ISSUE TITLE
Instance type requirement/choice

### ISSUE THREAD

**Issue by ironhouzi** [sethvargo/vault-on-gke#3]
`n1-standard-2` seems to be hard coded into the config. Is this a minimum requirement to run vault on GKE?

Would be nice to have some information on this, as it drastically affects the pricing.

**Comment by sethvargo** [comment]
It’s hard coded because I didn’t want to make every possible thing a variable. It’s possible to run Vault on both smaller and larger instances, and the requirement is based on your usage. For many users a standard-n1 would be fine. For others (because Vault is a CPU-intense application) it may actually require a highcpu-8. 

Your best bet is to instrument Vault by connecting it to a metric sink and see how much your Vault usage requires. 

I’d accept a PR to make that a variable, but unfortunately there’s many “right answers” here.
