### ISSUE TITLE
Does not work with new terraform (v0.11.11) ?

### ISSUE THREAD

**Issue by ypismerov** [sethvargo/vault-on-gke#38]
**What did you expect to happen?**

I remember it used to work, but not anymore. Looks like it started after I upgraded terrarorm to v0.11.11.

**What actually happened?**

terraform plan gives the error: "no vault token found"

$ terraform version
Terraform v0.11.11
+ provider.google v2.0.0
+ provider.google-beta v2.0.0
+ provider.helm v0.8.0
+ provider.http v1.0.1
+ provider.kubernetes v1.5.1
+ provider.local v1.1.0
+ provider.null v2.0.0
+ provider.random v2.0.0
+ provider.template v2.0.0
+ provider.tls v1.2.0
+ provider.vault v1.5.0

**Output**
```
Error: Error refreshing state: 1 error(s) occurred:

* provider.vault: no vault token found

```

**Comment by sethvargo** [comment]
There are no vault or helm resources in this repository. Perhaps you have an internal fork? If so, please check with the internal team.

The issue is happening because Terraform is looking for vault authentication (specifically at `~/.vault-token`), but you might be on a different workstation or have deleted that file.
