### ISSUE TITLE
New version of terraform 0.12

### ISSUE THREAD

**Issue by geordieboy23** [sethvargo/vault-on-gke#54]
$ terraform apply

Error: Invalid argument name

  on k8s.tf line 21, in resource "kubernetes_secret" "vault-tls":
  21:     "vault.crt" = "${tls_locally_signed_cert.vault.cert_pem}\n${tls_self_signed_cert.vault-ca.cert_pem}"

Argument names must not be quoted.

**Comment by sethvargo** [comment]
In Terraform 0.11, argument names must be quoted. Since the vast majority of users are still using 0.11, I'm holding off on updating until Terraform ~0.12.5 is released before updating this repo. There are still some bugs in 0.12 and this repo is used by a lot of enterprise customers that can't upgrade without vetting the new version first. Also, as you found, the changes are both forwards and backwards incompatible.

In the meantime, please use Terraform 0.11 with master or use the `sethvargo/12` branch.

#55
